# docker-compose prod.yml
version: '3'

services:
  db:
    image: postgres:13-alpine
    container_name: db
    env_file: 
      - ./prod.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis:alpine
    container_name: redis
    env_file: 
      - ./prod.env
    volumes:
      - redis_data:/data

  flask_auth:
    build: .
    container_name: flask_auth
    environment:
      - PYTHONPATH=/flask_auth
    env_file:
      - ./prod.env
    working_dir: /flask_auth
    depends_on:
      - redis
      - db
    restart: always

  nginx:
    container_name: nginx
    image: nginx:1.20.1-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/site.conf:/etc/nginx/conf.d/site.conf:ro
    ports:
      - "80:80"
    depends_on:
      - flask_auth

volumes:
  postgres_data:
  redis_data:
