# docker-compose-dev.yml
version: '3'

services:
  auth_db:
    image: postgres:13-alpine
    container_name: auth_db
    env_file: 
      - ./flask_auth/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432

  redis:
    image: redis:alpine
    container_name: redis
    env_file: 
      - ./flask_auth/.env
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379

  flask_auth:
    build: ./flask_auth
    image: flask_auth-image
    container_name: flask_auth
    environment:
      - PYTHONPATH=/flask_auth
      - TESTS=True
      - DEBUG=True
    working_dir: /flask_auth
    depends_on:
      - redis
      - auth_db
    restart: always
    ports:
      - 5000:5000

  tests:
    image: flask_auth-image
    container_name: tests
    working_dir: /flask_auth/tests/functional
    env_file:
      - ./flask_auth/tests/functional/.env
    environment:
      - PYTHONPATH=/flask_auth/
      - TESTS=True
    depends_on:
      - flask_auth
    entrypoint: >
      sh -c "pip install -r ./requirements.txt
      && pytest ./auth_tests -vv -s --log-level=INFO"

volumes:
  postgres_data:
  redis_data:
