# docker-compose-test.yml
version: '3'

services:
  auth_db:
    image: postgres:13-alpine
    container_name: auth_db
    env_file: 
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432

  redis:
    image: redis:alpine
    container_name: redis
    env_file: 
      - ./.env
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379

  flask_auth:
    build: ./flask_auth
    image: flask_auth-image
    container_name: flask_auth
    environment:
      - PYTHONPATH=/flask_auth
      - DEBUG=True
    working_dir: /flask_auth
    env_file: 
      - ./.env
    depends_on:
      - redis
      - auth_db
    restart: always
    ports:
      - 5000:5000

volumes:
  postgres_data:
  redis_data:
